name: Musify
description: Music Streaming and Downloading app made in Flutter!

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  # Migrated from audioplayers to just_audio for better features and performance
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  dart_des: ^1.0.1  # Pure Dart DES implementation (port of pyDES)
  # ext_storage: ^1.0.3
  path_provider: ^2.1.1  # Replaced ext_storage with path_provider
  # audiotagger: ^2.2.1  # Removed due to Android Gradle Plugin compatibility issues
  audiotags: ^1.4.5
  # progress_dialog: ^1.2.4
  flutter_easyloading: ^3.0.5  # Replaced progress_dialog with flutter_easyloading
  # gradient_widgets: ^0.6.0  # Temporarily disabled due to TextTheme.button compatibility issue
  gradient_widgets_plus: ^1.0.0
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.5
  cached_network_image: ^3.3.0
  provider: ^6.1.1  # State management solution following industry standards


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  win32: ^5.14.0  # Override to fix UnmodifiableUint8ListView compatibility issue

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Bold.ttf
        - asset: fonts/DMSans-Italic.ttf
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Medium.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
